field_types:
- lo_orderkey::int
- lo_linenumber::int
- lo_custkey::int
- lo_partkey::int
- lo_suppkey::int
- lo_orderdate::int
- lo_orderpriority::string
- lo_shippriority::string
- lo_quantity::int
- lo_extendedprice::int
- lo_ordtotalprice::int
- lo_discount::int
- lo_revenue::int
- lo_supplycost::int
- lo_tax::int
- lo_commitdate::int
- lo_shipmode::string
- c_custkey::int
- c_name::string
- c_address::string
- c_city::string
- c_nation::string
- c_region::string
- c_phone::string
- c_mktsegment::string
- p_partkey::int
- p_name::string
- p_mfgr::string
- p_category::string
- p_brand1::string
- p_color::string
- p_type::string
- p_size::int
- p_container::string
- s_suppkey::int
- s_name::string
- s_address::string
- s_city::string
- s_nation::string
- s_region::string
- s_phone::string
- d_datekey::int
- d_date::string
- d_dayofweek::string
- d_month::string
- d_year::int
- d_yearmonthnum::int
- d_yearmonth::string
- d_daynuminweek::int
- d_daynuminmonth::int
- d_daynuminyear::int
- d_monthnuminyear::int
- d_weeknuminyear::int
- d_sellingseason::string
- d_lastdayinweekfl::bool
- d_lastdayinmonthfl::bool
- d_holidayfl::bool
- d_weekdayfl::bool
clustering_key:
- d_year
- s_region
- c_region
- p_category
- d_monthnuminyear
